# Change these first
owner: cayepezg # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Mis Revistas
    url: https://www.misrevistas.com
    icon: https://www.misrevistas.com/img/favicon.ico
  - name: El Universal
    url: https://www.eluniversal.com
    icon: https://www.eluniversal.com/img/favicon.ico
  - name: Estampas
    url: https://www.estampas.com
    icon: https://www.estampas.com/images/favicon.ico
  - name: Notitarde
    url: https://www.notitarde.com.ve
    icon: https://www.notitarde.com/img/favico.jpg

assignees:
  - cayepezg
  
i18n:
  footer: "https://www.knoios.com"
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status MR
  introTitle: "**Estatus de Aplicaciones monitoreadas por CX**"
  introMessage: Esta página muestra los resultados del constante monitoreo de las aplicaciones servidas por CX.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
